;======================================================
; Hawkwynd Radio sc_serv configuration file
; last updated 1/20/23 
; =====================================================


publicserver=always
adminpassword=set_admin_password
password=set_account_password
requirestreamconfigs=1
streamautodumptime_1=180
autodumptime_1=180

; stream_1 configuration

streamadminpassword_1=admin_password
streamid_1=1
streampassword_1=admin_password
;serverport_1=8000
streampath_1=stream
streamauthhash_1=8A4BB7E5-9E83-4C69-8284-7D8C97BCAFD8


; IntroFile can specify a mp3 file that will be streamed to listeners right
; when they connect before they hear the live stream.
; Note that the intro file MUST be the same samplerate/channels as the
; live stream in order for this to work properly. Although bitrate CAN
; vary, you can use '%d' to specify the bitrate in the filename
; (i.e. C:\intro%d.mp3 would be C:\intro64.mp3 if you are casting at 64kbps).
; The default is no IntroFile

; ================================================================================================

; IntroFile=hawkad_nometa_64-44100.mp3 

; convert mp3 to 128k bitrate
; ffmpeg -v debug -i "hawkad1.mp3" -c:a libmp3lame -b:a 128k -ac 2 -ar 44100 -vn "hawkad128.mp3"
; --- currently, the stream will not continue playing after playing the intro file
; ================================================================================================

; stream_2 configuration

streamid_2=2
<<<<<<< HEAD
streampassword_2=scootre
streampath_2=mrblotto

; Introfile for blotto radio
;IntroFile=blottoIntro.mp3

=======
streampassword_2=password
; streamport_2=8000
streampath_2=test
>>>>>>> fd57628c51e4a172133dead8d47afe12eee956bb

; ambient stream configuration

streamid_3=3
<<<<<<< HEAD
streampassword_3=scootre
streampath_3=ambient
=======
streampassword_3=password
streampath_3=stream_name
>>>>>>> fd57628c51e4a172133dead8d47afe12eee956bb

; general configuration

logfile=logs/sc_serv.log
w3clog=logs/sc_w3c.log
banfile=control/sc_serv.ban
ripfile=control/sc_serv.rip

shoutcast1clientdebug=1
shoutcast2clientdebug=1
httpclientdebug=1
shoutcastsourcedebug=1
uvox2sourcedebug=1
httpsourcedebug=1
relayshoutcastdebug=1
relayuvoxdebug=1
relaydebug=1
httpstyledebug=1
webclientdebug=1
admetricsdebug=1
yp2debug=1
streamdatadebug=1
statsdebug=1
microserverdebug=1
threadrunnerdebug=1
forceshortsends=0
ratelimit=0
flvclientdebug=1
W3CEnable=Yes
<<<<<<< HEAD

; Mr. Blotto Radio 
streamauthhash_2=6e1e3d7e-f96e-4491-b3cd-c8bbf39ad6a7

; Ambient radio
streamauthhash_3=5ad7056f-82e3-4417-8813-94b23acff819
=======
streamauthhash_2=stream_auth_hash_from_shoutcast
streamauthhash_3=stream_auth_hash_from_shoutcast
>>>>>>> fd57628c51e4a172133dead8d47afe12eee956bb
