;======================================================
; Hawkwynd Radio sc_serv configuration file
; last updated 1/20/23 
; =====================================================

publicserver=always
adminpassword=redacted
password=redacted
requirestreamconfigs=1
streamautodumptime_1=180
autodumptime_1=180

; stream_1 configuration

streamadminpassword_1=redacted
streamid_1=1
streampassword_1=redacted
;serverport_1=8000
streampath_1=stream
streamauthhash_1=FDC1C391-A44D-47B5-840A-00C34DA9AA38


; IntroFile can specify a mp3 file that will be streamed to listeners right
; when they connect before they hear the live stream.
; Note that the intro file MUST be the same samplerate/channels as the
; live stream in order for this to work properly. Although bitrate CAN
; vary, you can use '%d' to specify the bitrate in the filename
; (i.e. C:\intro%d.mp3 would be C:\intro64.mp3 if you are casting at 64kbps).
; The default is no IntroFile

; ================================================================================================
; IntroFile=hawkad%d.mp3 
; convert mp3 to 128k bitrate
; ffmpeg -v debug -i "hawkad1.mp3" -c:a libmp3lame -b:a 128k -ac 2 -ar 44100 -vn "hawkad128.mp3"
; --- currently, the stream will not continue playing after playing the intro file
; ================================================================================================


; stream_2 configuration

streamid_2=2
streampassword_2=redacted
; streamport_2=8000
streampath_2=test

; ambient stream configuration
streamid_3=3
streampassword_3=redacted
streampath_3=ambient 

; general configuration

logfile=logs/sc_serv.log
w3clog=logs/sc_w3c.log
banfile=control/sc_serv.ban
ripfile=control/sc_serv.rip

shoutcast1clientdebug=0
shoutcast2clientdebug=0
httpclientdebug=0
shoutcastsourcedebug=0
uvox2sourcedebug=0
httpsourcedebug=0
relayshoutcastdebug=0
relayuvoxdebug=0
relaydebug=0
httpstyledebug=0
webclientdebug=0
admetricsdebug=0
yp2debug=0
streamdatadebug=0
statsdebug=0
microserverdebug=0
threadrunnerdebug=0
forceshortsends=1
ratelimit=0
flvclientdebug=0
W3CEnable=Yes
streamauthhash_2=2CFE193B-7B42-416C-A4B7-5F86BEEE0C6F
streamauthhash_3=5ad7056f-82e3-4417-8813-94b23acff819
